%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'DCP_D';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(10,1);
M_.exo_names_tex = cell(10,1);
M_.exo_names_long = cell(10,1);
M_.exo_names(1) = {'eps_i_U'};
M_.exo_names_tex(1) = {'eps\_i\_U'};
M_.exo_names_long(1) = {'eps_i_U'};
M_.exo_names(2) = {'eps_i_G'};
M_.exo_names_tex(2) = {'eps\_i\_G'};
M_.exo_names_long(2) = {'eps_i_G'};
M_.exo_names(3) = {'eps_i_R'};
M_.exo_names_tex(3) = {'eps\_i\_R'};
M_.exo_names_long(3) = {'eps_i_R'};
M_.exo_names(4) = {'eps_R'};
M_.exo_names_tex(4) = {'eps\_R'};
M_.exo_names_long(4) = {'eps_R'};
M_.exo_names(5) = {'eps_G'};
M_.exo_names_tex(5) = {'eps\_G'};
M_.exo_names_long(5) = {'eps_G'};
M_.exo_names(6) = {'eps_a_U'};
M_.exo_names_tex(6) = {'eps\_a\_U'};
M_.exo_names_long(6) = {'eps_a_U'};
M_.exo_names(7) = {'eps_a_G'};
M_.exo_names_tex(7) = {'eps\_a\_G'};
M_.exo_names_long(7) = {'eps_a_G'};
M_.exo_names(8) = {'eps_a_R'};
M_.exo_names_tex(8) = {'eps\_a\_R'};
M_.exo_names_long(8) = {'eps_a_R'};
M_.exo_names(9) = {'eps_uip_G'};
M_.exo_names_tex(9) = {'eps\_uip\_G'};
M_.exo_names_long(9) = {'eps_uip_G'};
M_.exo_names(10) = {'eps_uip_R'};
M_.exo_names_tex(10) = {'eps\_uip\_R'};
M_.exo_names_long(10) = {'eps_uip_R'};
M_.endo_names = cell(114,1);
M_.endo_names_tex = cell(114,1);
M_.endo_names_long = cell(114,1);
M_.endo_names(1) = {'p_UU'};
M_.endo_names_tex(1) = {'p\_UU'};
M_.endo_names_long(1) = {'p_UU'};
M_.endo_names(2) = {'p_GG'};
M_.endo_names_tex(2) = {'p\_GG'};
M_.endo_names_long(2) = {'p_GG'};
M_.endo_names(3) = {'p_RR'};
M_.endo_names_tex(3) = {'p\_RR'};
M_.endo_names_long(3) = {'p_RR'};
M_.endo_names(4) = {'p_UG'};
M_.endo_names_tex(4) = {'p\_UG'};
M_.endo_names_long(4) = {'p_UG'};
M_.endo_names(5) = {'p_UR'};
M_.endo_names_tex(5) = {'p\_UR'};
M_.endo_names_long(5) = {'p_UR'};
M_.endo_names(6) = {'p_GU'};
M_.endo_names_tex(6) = {'p\_GU'};
M_.endo_names_long(6) = {'p_GU'};
M_.endo_names(7) = {'p_GR'};
M_.endo_names_tex(7) = {'p\_GR'};
M_.endo_names_long(7) = {'p_GR'};
M_.endo_names(8) = {'p_RG'};
M_.endo_names_tex(8) = {'p\_RG'};
M_.endo_names_long(8) = {'p_RG'};
M_.endo_names(9) = {'p_RU'};
M_.endo_names_tex(9) = {'p\_RU'};
M_.endo_names_long(9) = {'p_RU'};
M_.endo_names(10) = {'p_UU_reset'};
M_.endo_names_tex(10) = {'p\_UU\_reset'};
M_.endo_names_long(10) = {'p_UU_reset'};
M_.endo_names(11) = {'p_GG_reset'};
M_.endo_names_tex(11) = {'p\_GG\_reset'};
M_.endo_names_long(11) = {'p_GG_reset'};
M_.endo_names(12) = {'p_RR_reset'};
M_.endo_names_tex(12) = {'p\_RR\_reset'};
M_.endo_names_long(12) = {'p_RR_reset'};
M_.endo_names(13) = {'c_U'};
M_.endo_names_tex(13) = {'c\_U'};
M_.endo_names_long(13) = {'c_U'};
M_.endo_names(14) = {'c_R'};
M_.endo_names_tex(14) = {'c\_R'};
M_.endo_names_long(14) = {'c_R'};
M_.endo_names(15) = {'c_G'};
M_.endo_names_tex(15) = {'c\_G'};
M_.endo_names_long(15) = {'c_G'};
M_.endo_names(16) = {'pi_U'};
M_.endo_names_tex(16) = {'pi\_U'};
M_.endo_names_long(16) = {'pi_U'};
M_.endo_names(17) = {'pi_R'};
M_.endo_names_tex(17) = {'pi\_R'};
M_.endo_names_long(17) = {'pi_R'};
M_.endo_names(18) = {'pi_G'};
M_.endo_names_tex(18) = {'pi\_G'};
M_.endo_names_long(18) = {'pi_G'};
M_.endo_names(19) = {'i_U'};
M_.endo_names_tex(19) = {'i\_U'};
M_.endo_names_long(19) = {'i_U'};
M_.endo_names(20) = {'i_R'};
M_.endo_names_tex(20) = {'i\_R'};
M_.endo_names_long(20) = {'i_R'};
M_.endo_names(21) = {'i_G'};
M_.endo_names_tex(21) = {'i\_G'};
M_.endo_names_long(21) = {'i_G'};
M_.endo_names(22) = {'i_U_G'};
M_.endo_names_tex(22) = {'i\_U\_G'};
M_.endo_names_long(22) = {'i_U_G'};
M_.endo_names(23) = {'i_U_R'};
M_.endo_names_tex(23) = {'i\_U\_R'};
M_.endo_names_long(23) = {'i_U_R'};
M_.endo_names(24) = {'B_U'};
M_.endo_names_tex(24) = {'B\_U'};
M_.endo_names_long(24) = {'B_U'};
M_.endo_names(25) = {'B_G'};
M_.endo_names_tex(25) = {'B\_G'};
M_.endo_names_long(25) = {'B_G'};
M_.endo_names(26) = {'B_R'};
M_.endo_names_tex(26) = {'B\_R'};
M_.endo_names_long(26) = {'B_R'};
M_.endo_names(27) = {'w_U'};
M_.endo_names_tex(27) = {'w\_U'};
M_.endo_names_long(27) = {'w_U'};
M_.endo_names(28) = {'w_G'};
M_.endo_names_tex(28) = {'w\_G'};
M_.endo_names_long(28) = {'w_G'};
M_.endo_names(29) = {'w_R'};
M_.endo_names_tex(29) = {'w\_R'};
M_.endo_names_long(29) = {'w_R'};
M_.endo_names(30) = {'n_U'};
M_.endo_names_tex(30) = {'n\_U'};
M_.endo_names_long(30) = {'n_U'};
M_.endo_names(31) = {'n_G'};
M_.endo_names_tex(31) = {'n\_G'};
M_.endo_names_long(31) = {'n_G'};
M_.endo_names(32) = {'n_R'};
M_.endo_names_tex(32) = {'n\_R'};
M_.endo_names_long(32) = {'n_R'};
M_.endo_names(33) = {'mc_U'};
M_.endo_names_tex(33) = {'mc\_U'};
M_.endo_names_long(33) = {'mc_U'};
M_.endo_names(34) = {'mc_G'};
M_.endo_names_tex(34) = {'mc\_G'};
M_.endo_names_long(34) = {'mc_G'};
M_.endo_names(35) = {'mc_R'};
M_.endo_names_tex(35) = {'mc\_R'};
M_.endo_names_long(35) = {'mc_R'};
M_.endo_names(36) = {'x_U'};
M_.endo_names_tex(36) = {'x\_U'};
M_.endo_names_long(36) = {'x_U'};
M_.endo_names(37) = {'x_G'};
M_.endo_names_tex(37) = {'x\_G'};
M_.endo_names_long(37) = {'x_G'};
M_.endo_names(38) = {'x_R'};
M_.endo_names_tex(38) = {'x\_R'};
M_.endo_names_long(38) = {'x_R'};
M_.endo_names(39) = {'y_U'};
M_.endo_names_tex(39) = {'y\_U'};
M_.endo_names_long(39) = {'y_U'};
M_.endo_names(40) = {'y_R'};
M_.endo_names_tex(40) = {'y\_R'};
M_.endo_names_long(40) = {'y_R'};
M_.endo_names(41) = {'y_G'};
M_.endo_names_tex(41) = {'y\_G'};
M_.endo_names_long(41) = {'y_G'};
M_.endo_names(42) = {'y_UU'};
M_.endo_names_tex(42) = {'y\_UU'};
M_.endo_names_long(42) = {'y_UU'};
M_.endo_names(43) = {'y_UG'};
M_.endo_names_tex(43) = {'y\_UG'};
M_.endo_names_long(43) = {'y_UG'};
M_.endo_names(44) = {'y_UR'};
M_.endo_names_tex(44) = {'y\_UR'};
M_.endo_names_long(44) = {'y_UR'};
M_.endo_names(45) = {'y_GG'};
M_.endo_names_tex(45) = {'y\_GG'};
M_.endo_names_long(45) = {'y_GG'};
M_.endo_names(46) = {'y_GU'};
M_.endo_names_tex(46) = {'y\_GU'};
M_.endo_names_long(46) = {'y_GU'};
M_.endo_names(47) = {'y_GR'};
M_.endo_names_tex(47) = {'y\_GR'};
M_.endo_names_long(47) = {'y_GR'};
M_.endo_names(48) = {'y_RR'};
M_.endo_names_tex(48) = {'y\_RR'};
M_.endo_names_long(48) = {'y_RR'};
M_.endo_names(49) = {'y_RU'};
M_.endo_names_tex(49) = {'y\_RU'};
M_.endo_names_long(49) = {'y_RU'};
M_.endo_names(50) = {'y_RG'};
M_.endo_names_tex(50) = {'y\_RG'};
M_.endo_names_long(50) = {'y_RG'};
M_.endo_names(51) = {'Profit_U'};
M_.endo_names_tex(51) = {'Profit\_U'};
M_.endo_names_long(51) = {'Profit_U'};
M_.endo_names(52) = {'Profit_G'};
M_.endo_names_tex(52) = {'Profit\_G'};
M_.endo_names_long(52) = {'Profit_G'};
M_.endo_names(53) = {'Profit_R'};
M_.endo_names_tex(53) = {'Profit\_R'};
M_.endo_names_long(53) = {'Profit_R'};
M_.endo_names(54) = {'q_G'};
M_.endo_names_tex(54) = {'q\_G'};
M_.endo_names_long(54) = {'q_G'};
M_.endo_names(55) = {'q_R'};
M_.endo_names_tex(55) = {'q\_R'};
M_.endo_names_long(55) = {'q_R'};
M_.endo_names(56) = {'eps_M_U'};
M_.endo_names_tex(56) = {'eps\_M\_U'};
M_.endo_names_long(56) = {'eps_M_U'};
M_.endo_names(57) = {'eps_M_G'};
M_.endo_names_tex(57) = {'eps\_M\_G'};
M_.endo_names_long(57) = {'eps_M_G'};
M_.endo_names(58) = {'eps_M_R'};
M_.endo_names_tex(58) = {'eps\_M\_R'};
M_.endo_names_long(58) = {'eps_M_R'};
M_.endo_names(59) = {'a_U'};
M_.endo_names_tex(59) = {'a\_U'};
M_.endo_names_long(59) = {'a_U'};
M_.endo_names(60) = {'a_G'};
M_.endo_names_tex(60) = {'a\_G'};
M_.endo_names_long(60) = {'a_G'};
M_.endo_names(61) = {'a_R'};
M_.endo_names_tex(61) = {'a\_R'};
M_.endo_names_long(61) = {'a_R'};
M_.endo_names(62) = {'uip_G'};
M_.endo_names_tex(62) = {'uip\_G'};
M_.endo_names_long(62) = {'uip_G'};
M_.endo_names(63) = {'uip_R'};
M_.endo_names_tex(63) = {'uip\_R'};
M_.endo_names_long(63) = {'uip_R'};
M_.endo_names(64) = {'y_U_UG'};
M_.endo_names_tex(64) = {'y\_U\_UG'};
M_.endo_names_long(64) = {'y_U_UG'};
M_.endo_names(65) = {'y_G_UG'};
M_.endo_names_tex(65) = {'y\_G\_UG'};
M_.endo_names_long(65) = {'y_G_UG'};
M_.endo_names(66) = {'p_U_UG'};
M_.endo_names_tex(66) = {'p\_U\_UG'};
M_.endo_names_long(66) = {'p_U_UG'};
M_.endo_names(67) = {'p_G_UG'};
M_.endo_names_tex(67) = {'p\_G\_UG'};
M_.endo_names_long(67) = {'p_G_UG'};
M_.endo_names(68) = {'p_U_UG_reset'};
M_.endo_names_tex(68) = {'p\_U\_UG\_reset'};
M_.endo_names_long(68) = {'p_U_UG_reset'};
M_.endo_names(69) = {'p_G_UG_reset'};
M_.endo_names_tex(69) = {'p\_G\_UG\_reset'};
M_.endo_names_long(69) = {'p_G_UG_reset'};
M_.endo_names(70) = {'y_U_UR'};
M_.endo_names_tex(70) = {'y\_U\_UR'};
M_.endo_names_long(70) = {'y_U_UR'};
M_.endo_names(71) = {'y_R_UR'};
M_.endo_names_tex(71) = {'y\_R\_UR'};
M_.endo_names_long(71) = {'y_R_UR'};
M_.endo_names(72) = {'p_U_UR'};
M_.endo_names_tex(72) = {'p\_U\_UR'};
M_.endo_names_long(72) = {'p_U_UR'};
M_.endo_names(73) = {'p_R_UR'};
M_.endo_names_tex(73) = {'p\_R\_UR'};
M_.endo_names_long(73) = {'p_R_UR'};
M_.endo_names(74) = {'p_U_UR_reset'};
M_.endo_names_tex(74) = {'p\_U\_UR\_reset'};
M_.endo_names_long(74) = {'p_U_UR_reset'};
M_.endo_names(75) = {'p_R_UR_reset'};
M_.endo_names_tex(75) = {'p\_R\_UR\_reset'};
M_.endo_names_long(75) = {'p_R_UR_reset'};
M_.endo_names(76) = {'y_U_GU'};
M_.endo_names_tex(76) = {'y\_U\_GU'};
M_.endo_names_long(76) = {'y_U_GU'};
M_.endo_names(77) = {'y_G_GU'};
M_.endo_names_tex(77) = {'y\_G\_GU'};
M_.endo_names_long(77) = {'y_G_GU'};
M_.endo_names(78) = {'p_U_GU'};
M_.endo_names_tex(78) = {'p\_U\_GU'};
M_.endo_names_long(78) = {'p_U_GU'};
M_.endo_names(79) = {'p_G_GU'};
M_.endo_names_tex(79) = {'p\_G\_GU'};
M_.endo_names_long(79) = {'p_G_GU'};
M_.endo_names(80) = {'p_U_GU_reset'};
M_.endo_names_tex(80) = {'p\_U\_GU\_reset'};
M_.endo_names_long(80) = {'p_U_GU_reset'};
M_.endo_names(81) = {'p_G_GU_reset'};
M_.endo_names_tex(81) = {'p\_G\_GU\_reset'};
M_.endo_names_long(81) = {'p_G_GU_reset'};
M_.endo_names(82) = {'y_R_GR'};
M_.endo_names_tex(82) = {'y\_R\_GR'};
M_.endo_names_long(82) = {'y_R_GR'};
M_.endo_names(83) = {'y_G_GR'};
M_.endo_names_tex(83) = {'y\_G\_GR'};
M_.endo_names_long(83) = {'y_G_GR'};
M_.endo_names(84) = {'y_U_GR'};
M_.endo_names_tex(84) = {'y\_U\_GR'};
M_.endo_names_long(84) = {'y_U_GR'};
M_.endo_names(85) = {'p_R_GR'};
M_.endo_names_tex(85) = {'p\_R\_GR'};
M_.endo_names_long(85) = {'p_R_GR'};
M_.endo_names(86) = {'p_G_GR'};
M_.endo_names_tex(86) = {'p\_G\_GR'};
M_.endo_names_long(86) = {'p_G_GR'};
M_.endo_names(87) = {'p_U_GR'};
M_.endo_names_tex(87) = {'p\_U\_GR'};
M_.endo_names_long(87) = {'p_U_GR'};
M_.endo_names(88) = {'p_R_GR_reset'};
M_.endo_names_tex(88) = {'p\_R\_GR\_reset'};
M_.endo_names_long(88) = {'p_R_GR_reset'};
M_.endo_names(89) = {'p_G_GR_reset'};
M_.endo_names_tex(89) = {'p\_G\_GR\_reset'};
M_.endo_names_long(89) = {'p_G_GR_reset'};
M_.endo_names(90) = {'p_U_GR_reset'};
M_.endo_names_tex(90) = {'p\_U\_GR\_reset'};
M_.endo_names_long(90) = {'p_U_GR_reset'};
M_.endo_names(91) = {'y_U_RU'};
M_.endo_names_tex(91) = {'y\_U\_RU'};
M_.endo_names_long(91) = {'y_U_RU'};
M_.endo_names(92) = {'y_R_RU'};
M_.endo_names_tex(92) = {'y\_R\_RU'};
M_.endo_names_long(92) = {'y_R_RU'};
M_.endo_names(93) = {'p_U_RU'};
M_.endo_names_tex(93) = {'p\_U\_RU'};
M_.endo_names_long(93) = {'p_U_RU'};
M_.endo_names(94) = {'p_R_RU'};
M_.endo_names_tex(94) = {'p\_R\_RU'};
M_.endo_names_long(94) = {'p_R_RU'};
M_.endo_names(95) = {'p_U_RU_reset'};
M_.endo_names_tex(95) = {'p\_U\_RU\_reset'};
M_.endo_names_long(95) = {'p_U_RU_reset'};
M_.endo_names(96) = {'p_R_RU_reset'};
M_.endo_names_tex(96) = {'p\_R\_RU\_reset'};
M_.endo_names_long(96) = {'p_R_RU_reset'};
M_.endo_names(97) = {'y_R_RG'};
M_.endo_names_tex(97) = {'y\_R\_RG'};
M_.endo_names_long(97) = {'y_R_RG'};
M_.endo_names(98) = {'y_G_RG'};
M_.endo_names_tex(98) = {'y\_G\_RG'};
M_.endo_names_long(98) = {'y_G_RG'};
M_.endo_names(99) = {'y_U_RG'};
M_.endo_names_tex(99) = {'y\_U\_RG'};
M_.endo_names_long(99) = {'y_U_RG'};
M_.endo_names(100) = {'p_R_RG'};
M_.endo_names_tex(100) = {'p\_R\_RG'};
M_.endo_names_long(100) = {'p_R_RG'};
M_.endo_names(101) = {'p_G_RG'};
M_.endo_names_tex(101) = {'p\_G\_RG'};
M_.endo_names_long(101) = {'p_G_RG'};
M_.endo_names(102) = {'p_U_RG'};
M_.endo_names_tex(102) = {'p\_U\_RG'};
M_.endo_names_long(102) = {'p_U_RG'};
M_.endo_names(103) = {'p_R_RG_reset'};
M_.endo_names_tex(103) = {'p\_R\_RG\_reset'};
M_.endo_names_long(103) = {'p_R_RG_reset'};
M_.endo_names(104) = {'p_G_RG_reset'};
M_.endo_names_tex(104) = {'p\_G\_RG\_reset'};
M_.endo_names_long(104) = {'p_G_RG_reset'};
M_.endo_names(105) = {'p_U_RG_reset'};
M_.endo_names_tex(105) = {'p\_U\_RG\_reset'};
M_.endo_names_long(105) = {'p_U_RG_reset'};
M_.endo_names(106) = {'d_y_U'};
M_.endo_names_tex(106) = {'d\_y\_U'};
M_.endo_names_long(106) = {'d_y_U'};
M_.endo_names(107) = {'d_i_U'};
M_.endo_names_tex(107) = {'d\_i\_U'};
M_.endo_names_long(107) = {'d_i_U'};
M_.endo_names(108) = {'d_pi_U'};
M_.endo_names_tex(108) = {'d\_pi\_U'};
M_.endo_names_long(108) = {'d_pi_U'};
M_.endo_names(109) = {'d_w_U'};
M_.endo_names_tex(109) = {'d\_w\_U'};
M_.endo_names_long(109) = {'d_w_U'};
M_.endo_names(110) = {'d_y_G'};
M_.endo_names_tex(110) = {'d\_y\_G'};
M_.endo_names_long(110) = {'d_y_G'};
M_.endo_names(111) = {'d_i_G'};
M_.endo_names_tex(111) = {'d\_i\_G'};
M_.endo_names_long(111) = {'d_i_G'};
M_.endo_names(112) = {'d_pi_G'};
M_.endo_names_tex(112) = {'d\_pi\_G'};
M_.endo_names_long(112) = {'d_pi_G'};
M_.endo_names(113) = {'d_w_G'};
M_.endo_names_tex(113) = {'d\_w\_G'};
M_.endo_names_long(113) = {'d_w_G'};
M_.endo_names(114) = {'d_q_G'};
M_.endo_names_tex(114) = {'d\_q\_G'};
M_.endo_names_long(114) = {'d_q_G'};
M_.endo_partitions = struct();
M_.param_names = cell(68,1);
M_.param_names_tex = cell(68,1);
M_.param_names_long = cell(68,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'alpha'};
M_.param_names_tex(2) = {'alpha'};
M_.param_names_long(2) = {'alpha'};
M_.param_names(3) = {'alphatilde'};
M_.param_names_tex(3) = {'alphatilde'};
M_.param_names_long(3) = {'alphatilde'};
M_.param_names(4) = {'sigma'};
M_.param_names_tex(4) = {'sigma'};
M_.param_names_long(4) = {'sigma'};
M_.param_names(5) = {'sigma_c'};
M_.param_names_tex(5) = {'sigma\_c'};
M_.param_names_long(5) = {'sigma_c'};
M_.param_names(6) = {'varphi'};
M_.param_names_tex(6) = {'varphi'};
M_.param_names_long(6) = {'varphi'};
M_.param_names(7) = {'kappa'};
M_.param_names_tex(7) = {'kappa'};
M_.param_names_long(7) = {'kappa'};
M_.param_names(8) = {'gamma'};
M_.param_names_tex(8) = {'gamma'};
M_.param_names_long(8) = {'gamma'};
M_.param_names(9) = {'i_star'};
M_.param_names_tex(9) = {'i\_star'};
M_.param_names_long(9) = {'i_star'};
M_.param_names(10) = {'psi'};
M_.param_names_tex(10) = {'psi'};
M_.param_names_long(10) = {'psi'};
M_.param_names(11) = {'B_bar'};
M_.param_names_tex(11) = {'B\_bar'};
M_.param_names_long(11) = {'B_bar'};
M_.param_names(12) = {'eta'};
M_.param_names_tex(12) = {'eta'};
M_.param_names_long(12) = {'eta'};
M_.param_names(13) = {'mu_W'};
M_.param_names_tex(13) = {'mu\_W'};
M_.param_names_long(13) = {'mu_W'};
M_.param_names(14) = {'theta_p'};
M_.param_names_tex(14) = {'theta\_p'};
M_.param_names_long(14) = {'theta_p'};
M_.param_names(15) = {'theta_W'};
M_.param_names_tex(15) = {'theta\_W'};
M_.param_names_long(15) = {'theta_W'};
M_.param_names(16) = {'lambda_W'};
M_.param_names_tex(16) = {'lambda\_W'};
M_.param_names_long(16) = {'lambda_W'};
M_.param_names(17) = {'rho_m'};
M_.param_names_tex(17) = {'rho\_m'};
M_.param_names_long(17) = {'rho_m'};
M_.param_names(18) = {'rho_eps'};
M_.param_names_tex(18) = {'rho\_eps'};
M_.param_names_long(18) = {'rho_eps'};
M_.param_names(19) = {'phi_M'};
M_.param_names_tex(19) = {'phi\_M'};
M_.param_names_long(19) = {'phi_M'};
M_.param_names(20) = {'zeta'};
M_.param_names_tex(20) = {'zeta'};
M_.param_names_long(20) = {'zeta'};
M_.param_names(21) = {'varepsilon'};
M_.param_names_tex(21) = {'varepsilon'};
M_.param_names_long(21) = {'varepsilon'};
M_.param_names(22) = {'Gamma'};
M_.param_names_tex(22) = {'Gamma'};
M_.param_names_long(22) = {'Gamma'};
M_.param_names(23) = {'mu_bar'};
M_.param_names_tex(23) = {'mu\_bar'};
M_.param_names_long(23) = {'mu_bar'};
M_.param_names(24) = {'stdm'};
M_.param_names_tex(24) = {'stdm'};
M_.param_names_long(24) = {'stdm'};
M_.param_names(25) = {'a_bar'};
M_.param_names_tex(25) = {'a\_bar'};
M_.param_names_long(25) = {'a_bar'};
M_.param_names(26) = {'rho_a'};
M_.param_names_tex(26) = {'rho\_a'};
M_.param_names_long(26) = {'rho_a'};
M_.param_names(27) = {'std_a'};
M_.param_names_tex(27) = {'std\_a'};
M_.param_names_long(27) = {'std_a'};
M_.param_names(28) = {'rho_uip'};
M_.param_names_tex(28) = {'rho\_uip'};
M_.param_names_long(28) = {'rho_uip'};
M_.param_names(29) = {'std_uip'};
M_.param_names_tex(29) = {'std\_uip'};
M_.param_names_long(29) = {'std_uip'};
M_.param_names(30) = {'phi_Y'};
M_.param_names_tex(30) = {'phi\_Y'};
M_.param_names_long(30) = {'phi_Y'};
M_.param_names(31) = {'yflex'};
M_.param_names_tex(31) = {'yflex'};
M_.param_names_long(31) = {'yflex'};
M_.param_names(32) = {'habit'};
M_.param_names_tex(32) = {'habit'};
M_.param_names_long(32) = {'habit'};
M_.param_names(33) = {'theta_U_UG'};
M_.param_names_tex(33) = {'theta\_U\_UG'};
M_.param_names_long(33) = {'theta_U_UG'};
M_.param_names(34) = {'theta_G_UG'};
M_.param_names_tex(34) = {'theta\_G\_UG'};
M_.param_names_long(34) = {'theta_G_UG'};
M_.param_names(35) = {'theta_U_UR'};
M_.param_names_tex(35) = {'theta\_U\_UR'};
M_.param_names_long(35) = {'theta_U_UR'};
M_.param_names(36) = {'theta_R_UR'};
M_.param_names_tex(36) = {'theta\_R\_UR'};
M_.param_names_long(36) = {'theta_R_UR'};
M_.param_names(37) = {'theta_U_GU'};
M_.param_names_tex(37) = {'theta\_U\_GU'};
M_.param_names_long(37) = {'theta_U_GU'};
M_.param_names(38) = {'theta_G_GU'};
M_.param_names_tex(38) = {'theta\_G\_GU'};
M_.param_names_long(38) = {'theta_G_GU'};
M_.param_names(39) = {'theta_R_GR'};
M_.param_names_tex(39) = {'theta\_R\_GR'};
M_.param_names_long(39) = {'theta_R_GR'};
M_.param_names(40) = {'theta_G_GR'};
M_.param_names_tex(40) = {'theta\_G\_GR'};
M_.param_names_long(40) = {'theta_G_GR'};
M_.param_names(41) = {'theta_U_GR'};
M_.param_names_tex(41) = {'theta\_U\_GR'};
M_.param_names_long(41) = {'theta_U_GR'};
M_.param_names(42) = {'theta_U_RU'};
M_.param_names_tex(42) = {'theta\_U\_RU'};
M_.param_names_long(42) = {'theta_U_RU'};
M_.param_names(43) = {'theta_R_RU'};
M_.param_names_tex(43) = {'theta\_R\_RU'};
M_.param_names_long(43) = {'theta_R_RU'};
M_.param_names(44) = {'theta_R_RG'};
M_.param_names_tex(44) = {'theta\_R\_RG'};
M_.param_names_long(44) = {'theta_R_RG'};
M_.param_names(45) = {'theta_G_RG'};
M_.param_names_tex(45) = {'theta\_G\_RG'};
M_.param_names_long(45) = {'theta_G_RG'};
M_.param_names(46) = {'theta_U_RG'};
M_.param_names_tex(46) = {'theta\_U\_RG'};
M_.param_names_long(46) = {'theta_U_RG'};
M_.param_names(47) = {'phi_pi_U'};
M_.param_names_tex(47) = {'phi\_pi\_U'};
M_.param_names_long(47) = {'phi_pi_U'};
M_.param_names(48) = {'phi_pi_G'};
M_.param_names_tex(48) = {'phi\_pi\_G'};
M_.param_names_long(48) = {'phi_pi_G'};
M_.param_names(49) = {'phi_pi_R'};
M_.param_names_tex(49) = {'phi\_pi\_R'};
M_.param_names_long(49) = {'phi_pi_R'};
M_.param_names(50) = {'phi_Y_U'};
M_.param_names_tex(50) = {'phi\_Y\_U'};
M_.param_names_long(50) = {'phi_Y_U'};
M_.param_names(51) = {'phi_Y_G'};
M_.param_names_tex(51) = {'phi\_Y\_G'};
M_.param_names_long(51) = {'phi_Y_G'};
M_.param_names(52) = {'phi_Y_R'};
M_.param_names_tex(52) = {'phi\_Y\_R'};
M_.param_names_long(52) = {'phi_Y_R'};
M_.param_names(53) = {'rho_m_U'};
M_.param_names_tex(53) = {'rho\_m\_U'};
M_.param_names_long(53) = {'rho_m_U'};
M_.param_names(54) = {'rho_m_G'};
M_.param_names_tex(54) = {'rho\_m\_G'};
M_.param_names_long(54) = {'rho_m_G'};
M_.param_names(55) = {'rho_eps_U'};
M_.param_names_tex(55) = {'rho\_eps\_U'};
M_.param_names_long(55) = {'rho_eps_U'};
M_.param_names(56) = {'rho_eps_G'};
M_.param_names_tex(56) = {'rho\_eps\_G'};
M_.param_names_long(56) = {'rho_eps_G'};
M_.param_names(57) = {'rho_uip_G'};
M_.param_names_tex(57) = {'rho\_uip\_G'};
M_.param_names_long(57) = {'rho_uip_G'};
M_.param_names(58) = {'rho_a_U'};
M_.param_names_tex(58) = {'rho\_a\_U'};
M_.param_names_long(58) = {'rho_a_U'};
M_.param_names(59) = {'rho_a_G'};
M_.param_names_tex(59) = {'rho\_a\_G'};
M_.param_names_long(59) = {'rho_a_G'};
M_.param_names(60) = {'theta_p_U'};
M_.param_names_tex(60) = {'theta\_p\_U'};
M_.param_names_long(60) = {'theta_p_U'};
M_.param_names(61) = {'theta_W_U'};
M_.param_names_tex(61) = {'theta\_W\_U'};
M_.param_names_long(61) = {'theta_W_U'};
M_.param_names(62) = {'lambda_W_U'};
M_.param_names_tex(62) = {'lambda\_W\_U'};
M_.param_names_long(62) = {'lambda_W_U'};
M_.param_names(63) = {'theta_p_G'};
M_.param_names_tex(63) = {'theta\_p\_G'};
M_.param_names_long(63) = {'theta_p_G'};
M_.param_names(64) = {'theta_W_G'};
M_.param_names_tex(64) = {'theta\_W\_G'};
M_.param_names_long(64) = {'theta_W_G'};
M_.param_names(65) = {'lambda_W_G'};
M_.param_names_tex(65) = {'lambda\_W\_G'};
M_.param_names_long(65) = {'lambda_W_G'};
M_.param_names(66) = {'theta_p_R'};
M_.param_names_tex(66) = {'theta\_p\_R'};
M_.param_names_long(66) = {'theta_p_R'};
M_.param_names(67) = {'theta_W_R'};
M_.param_names_tex(67) = {'theta\_W\_R'};
M_.param_names_long(67) = {'theta_W_R'};
M_.param_names(68) = {'lambda_W_R'};
M_.param_names_tex(68) = {'lambda\_W\_R'};
M_.param_names_long(68) = {'lambda_W_R'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 10;
M_.endo_nbr = 114;
M_.param_nbr = 68;
M_.orig_endo_nbr = 114;
M_.aux_vars = [];
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'d_y_U'};
options_.varobs(2)  = {'d_i_U'};
options_.varobs(3)  = {'d_pi_U'};
options_.varobs(4)  = {'d_y_G'};
options_.varobs(5)  = {'d_i_G'};
options_.varobs(6)  = {'d_pi_G'};
options_.varobs(7)  = {'d_q_G'};
options_.varobs_id = [ 106 107 108 110 111 112 114  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(10, 10);
M_.Correlation_matrix = eye(10, 10);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [1 2 3 4 5 6 7 12 13 14 19 20 21 22 27 28 29 30 37 38 39 40 45 46 47 48 70 71 72 73 74 75 76 77 81 82 83 84 85 86 87 88 89 90 91];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 114;
M_.eq_nbr = 114;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 39 0;
 2 40 0;
 3 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 153;
 0 49 154;
 0 50 155;
 4 51 156;
 5 52 157;
 6 53 158;
 0 54 159;
 0 55 160;
 0 56 161;
 7 57 0;
 8 58 0;
 9 59 0;
 10 60 0;
 11 61 0;
 0 62 0;
 12 63 0;
 13 64 0;
 14 65 162;
 15 66 163;
 16 67 164;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 165;
 0 93 166;
 17 94 0;
 18 95 0;
 19 96 0;
 20 97 0;
 21 98 0;
 22 99 0;
 23 100 0;
 24 101 0;
 0 102 0;
 0 103 0;
 25 104 0;
 26 105 0;
 0 106 167;
 0 107 168;
 0 108 0;
 0 109 0;
 27 110 0;
 28 111 0;
 0 112 169;
 0 113 170;
 0 114 0;
 0 115 0;
 29 116 0;
 30 117 0;
 0 118 171;
 0 119 172;
 0 120 0;
 0 121 0;
 0 122 0;
 31 123 0;
 32 124 0;
 33 125 0;
 0 126 173;
 0 127 174;
 0 128 175;
 0 129 0;
 0 130 0;
 34 131 0;
 35 132 0;
 0 133 176;
 0 134 177;
 0 135 0;
 0 136 0;
 0 137 0;
 36 138 0;
 37 139 0;
 38 140 0;
 0 141 178;
 0 142 179;
 0 143 180;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 0 152 0;]';
M_.nstatic = 54;
M_.nfwrd   = 22;
M_.npred   = 32;
M_.nboth   = 6;
M_.nsfwrd   = 28;
M_.nspred   = 38;
M_.ndynamic   = 60;
M_.dynamic_tmp_nbr = [41; 43; 14; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , '1' ;
  2 , 'name' , '2' ;
  3 , 'name' , '3' ;
  4 , 'name' , '4' ;
  5 , 'name' , '5' ;
  6 , 'name' , '6' ;
  7 , 'name' , '7' ;
  8 , 'name' , 'p_U_UG_reset' ;
  9 , 'name' , 'p_G_UG_reset' ;
  10 , 'name' , '10' ;
  11 , 'name' , '11' ;
  12 , 'name' , '12' ;
  13 , 'name' , '13' ;
  14 , 'name' , '14' ;
  15 , 'name' , 'p_U_UR_reset' ;
  16 , 'name' , 'p_R_UR_reset' ;
  17 , 'name' , '17' ;
  18 , 'name' , '18' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , '22' ;
  23 , 'name' , 'p_U_GU_reset' ;
  24 , 'name' , 'p_G_GU_reset' ;
  25 , 'name' , '25' ;
  26 , 'name' , '26' ;
  27 , 'name' , '27' ;
  28 , 'name' , '28' ;
  29 , 'name' , '29' ;
  30 , 'name' , '30' ;
  31 , 'name' , 'p_R_GR_reset' ;
  32 , 'name' , 'p_G_GR_reset' ;
  33 , 'name' , 'p_U_GR_reset' ;
  34 , 'name' , '34' ;
  35 , 'name' , '35' ;
  36 , 'name' , '36' ;
  37 , 'name' , '37' ;
  38 , 'name' , '38' ;
  39 , 'name' , '39' ;
  40 , 'name' , '40' ;
  41 , 'name' , 'p_U_RU_reset' ;
  42 , 'name' , 'p_R_RU_reset' ;
  43 , 'name' , '43' ;
  44 , 'name' , '44' ;
  45 , 'name' , '45' ;
  46 , 'name' , '46' ;
  47 , 'name' , '47' ;
  48 , 'name' , '48' ;
  49 , 'name' , 'p_R_RG_reset' ;
  50 , 'name' , 'p_G_RG_reset' ;
  51 , 'name' , 'p_U_RG_reset' ;
  52 , 'name' , '52' ;
  53 , 'name' , '53' ;
  54 , 'name' , '54' ;
  55 , 'name' , '55' ;
  56 , 'name' , '56' ;
  57 , 'name' , '57' ;
  58 , 'name' , 'p_UU_reset' ;
  59 , 'name' , 'p_GG_reset' ;
  60 , 'name' , 'p_RR_reset' ;
  61 , 'name' , '61' ;
  62 , 'name' , '62' ;
  63 , 'name' , '63' ;
  64 , 'name' , 'p_UR' ;
  65 , 'name' , 'p_RU' ;
  66 , 'name' , 'p_UG' ;
  67 , 'name' , 'p_GU' ;
  68 , 'name' , 'p_GR' ;
  69 , 'name' , 'p_RG' ;
  70 , 'name' , 'Profit_U' ;
  71 , 'name' , 'Profit_G' ;
  72 , 'name' , 'Profit_R' ;
  73 , 'name' , '73' ;
  74 , 'name' , '74' ;
  75 , 'name' , '75' ;
  76 , 'name' , '76' ;
  77 , 'name' , '77' ;
  78 , 'name' , '78' ;
  79 , 'name' , '79' ;
  80 , 'name' , '80' ;
  81 , 'name' , 'mc_U' ;
  82 , 'name' , 'mc_G' ;
  83 , 'name' , 'mc_R' ;
  84 , 'name' , '84' ;
  85 , 'name' , '85' ;
  86 , 'name' , '86' ;
  87 , 'name' , '87' ;
  88 , 'name' , '88' ;
  89 , 'name' , '89' ;
  90 , 'name' , 'i_U_G' ;
  91 , 'name' , 'i_U_R' ;
  92 , 'name' , '92' ;
  93 , 'name' , '93' ;
  94 , 'name' , '94' ;
  95 , 'name' , '95' ;
  96 , 'name' , '96' ;
  97 , 'name' , '97' ;
  98 , 'name' , 'eps_M_U' ;
  99 , 'name' , 'eps_M_G' ;
  100 , 'name' , 'eps_M_R' ;
  101 , 'name' , 'uip_G' ;
  102 , 'name' , 'uip_R' ;
  103 , 'name' , '103' ;
  104 , 'name' , '104' ;
  105 , 'name' , '105' ;
  106 , 'name' , 'd_y_U' ;
  107 , 'name' , 'd_i_U' ;
  108 , 'name' , 'd_pi_U' ;
  109 , 'name' , 'd_w_U' ;
  110 , 'name' , 'd_y_G' ;
  111 , 'name' , 'd_i_G' ;
  112 , 'name' , 'd_pi_G' ;
  113 , 'name' , 'd_w_G' ;
  114 , 'name' , 'd_q_G' ;
};
M_.mapping.p_UU.eqidx = [4 55 61 70 ];
M_.mapping.p_GG.eqidx = [19 56 62 71 ];
M_.mapping.p_RR.eqidx = [37 57 63 72 ];
M_.mapping.p_UG.eqidx = [66 ];
M_.mapping.p_UR.eqidx = [64 ];
M_.mapping.p_GU.eqidx = [67 ];
M_.mapping.p_GR.eqidx = [68 ];
M_.mapping.p_RG.eqidx = [69 ];
M_.mapping.p_RU.eqidx = [65 ];
M_.mapping.p_UU_reset.eqidx = [58 61 ];
M_.mapping.p_GG_reset.eqidx = [59 62 ];
M_.mapping.p_RR_reset.eqidx = [60 63 ];
M_.mapping.c_U.eqidx = [4 21 22 39 40 73 78 ];
M_.mapping.c_R.eqidx = [13 14 28 29 30 37 75 77 80 ];
M_.mapping.c_G.eqidx = [6 7 19 46 47 48 74 76 79 ];
M_.mapping.pi_U.eqidx = [8 10 15 17 23 25 33 36 41 43 51 54 58 61 73 76 77 78 92 95 96 108 ];
M_.mapping.pi_R.eqidx = [16 18 31 34 42 44 49 52 60 63 75 80 94 96 ];
M_.mapping.pi_G.eqidx = [9 11 24 26 32 35 50 53 59 62 74 79 93 95 112 ];
M_.mapping.i_U.eqidx = [73 81 90 91 92 107 ];
M_.mapping.i_R.eqidx = [75 94 96 ];
M_.mapping.i_G.eqidx = [74 93 95 111 ];
M_.mapping.i_U_G.eqidx = [76 82 90 95 ];
M_.mapping.i_U_R.eqidx = [77 83 91 96 ];
M_.mapping.B_U.eqidx = [97 ];
M_.mapping.B_G.eqidx = [76 90 97 ];
M_.mapping.B_R.eqidx = [77 91 97 ];
M_.mapping.w_U.eqidx = [78 81 84 109 ];
M_.mapping.w_G.eqidx = [76 79 82 85 113 ];
M_.mapping.w_R.eqidx = [77 80 83 86 ];
M_.mapping.n_U.eqidx = [78 84 ];
M_.mapping.n_G.eqidx = [76 79 85 ];
M_.mapping.n_R.eqidx = [77 80 86 ];
M_.mapping.mc_U.eqidx = [8 9 15 16 58 70 81 84 87 ];
M_.mapping.mc_G.eqidx = [23 24 31 32 33 59 71 82 85 88 ];
M_.mapping.mc_R.eqidx = [41 42 49 50 51 60 72 83 86 89 ];
M_.mapping.x_U.eqidx = [4 21 22 39 40 87 ];
M_.mapping.x_G.eqidx = [6 7 19 46 47 48 88 ];
M_.mapping.x_R.eqidx = [13 14 28 29 30 37 89 ];
M_.mapping.y_U.eqidx = [1 70 84 87 92 106 ];
M_.mapping.y_R.eqidx = [3 72 86 89 94 ];
M_.mapping.y_G.eqidx = [2 71 85 88 93 110 ];
M_.mapping.y_UU.eqidx = [1 4 70 ];
M_.mapping.y_UG.eqidx = [1 5 ];
M_.mapping.y_UR.eqidx = [1 12 ];
M_.mapping.y_GG.eqidx = [2 19 71 ];
M_.mapping.y_GU.eqidx = [2 20 ];
M_.mapping.y_GR.eqidx = [2 27 ];
M_.mapping.y_RR.eqidx = [3 37 72 ];
M_.mapping.y_RU.eqidx = [3 38 ];
M_.mapping.y_RG.eqidx = [3 45 ];
M_.mapping.Profit_U.eqidx = [70 ];
M_.mapping.Profit_G.eqidx = [71 76 ];
M_.mapping.Profit_R.eqidx = [72 77 ];
M_.mapping.q_G.eqidx = [6 8 9 22 23 24 29 31 33 46 48 49 50 51 55 56 57 70 71 72 76 95 114 ];
M_.mapping.q_R.eqidx = [13 15 16 29 30 31 32 33 40 41 42 46 50 51 55 56 57 70 71 72 77 96 ];
M_.mapping.eps_M_U.eqidx = [92 98 ];
M_.mapping.eps_M_G.eqidx = [93 99 ];
M_.mapping.eps_M_R.eqidx = [94 100 ];
M_.mapping.a_U.eqidx = [81 103 ];
M_.mapping.a_G.eqidx = [82 104 ];
M_.mapping.a_R.eqidx = [83 105 ];
M_.mapping.uip_G.eqidx = [95 101 ];
M_.mapping.uip_R.eqidx = [96 102 ];
M_.mapping.y_U_UG.eqidx = [5 6 70 ];
M_.mapping.y_G_UG.eqidx = [5 7 70 ];
M_.mapping.p_U_UG.eqidx = [6 10 56 66 70 ];
M_.mapping.p_G_UG.eqidx = [7 11 56 66 70 ];
M_.mapping.p_U_UG_reset.eqidx = [8 10 ];
M_.mapping.p_G_UG_reset.eqidx = [9 11 ];
M_.mapping.y_U_UR.eqidx = [12 13 70 ];
M_.mapping.y_R_UR.eqidx = [12 14 70 ];
M_.mapping.p_U_UR.eqidx = [13 17 57 64 70 ];
M_.mapping.p_R_UR.eqidx = [14 18 57 64 70 ];
M_.mapping.p_U_UR_reset.eqidx = [15 17 ];
M_.mapping.p_R_UR_reset.eqidx = [16 18 ];
M_.mapping.y_U_GU.eqidx = [20 21 71 ];
M_.mapping.y_G_GU.eqidx = [20 22 71 ];
M_.mapping.p_U_GU.eqidx = [21 25 55 67 71 ];
M_.mapping.p_G_GU.eqidx = [22 26 55 67 71 ];
M_.mapping.p_U_GU_reset.eqidx = [23 25 ];
M_.mapping.p_G_GU_reset.eqidx = [24 26 ];
M_.mapping.y_R_GR.eqidx = [27 28 71 ];
M_.mapping.y_G_GR.eqidx = [27 29 71 ];
M_.mapping.y_U_GR.eqidx = [27 30 71 ];
M_.mapping.p_R_GR.eqidx = [28 34 57 68 71 ];
M_.mapping.p_G_GR.eqidx = [29 35 57 68 71 ];
M_.mapping.p_U_GR.eqidx = [30 36 57 68 71 ];
M_.mapping.p_R_GR_reset.eqidx = [31 34 ];
M_.mapping.p_G_GR_reset.eqidx = [32 35 ];
M_.mapping.p_U_GR_reset.eqidx = [33 36 ];
M_.mapping.y_U_RU.eqidx = [38 39 72 ];
M_.mapping.y_R_RU.eqidx = [38 40 72 ];
M_.mapping.p_U_RU.eqidx = [39 43 55 65 72 ];
M_.mapping.p_R_RU.eqidx = [40 44 55 65 72 ];
M_.mapping.p_U_RU_reset.eqidx = [41 43 ];
M_.mapping.p_R_RU_reset.eqidx = [42 44 ];
M_.mapping.y_R_RG.eqidx = [45 46 72 ];
M_.mapping.y_G_RG.eqidx = [45 47 72 ];
M_.mapping.y_U_RG.eqidx = [45 48 72 ];
M_.mapping.p_R_RG.eqidx = [46 52 56 69 72 ];
M_.mapping.p_G_RG.eqidx = [47 53 56 69 72 ];
M_.mapping.p_U_RG.eqidx = [48 54 56 69 72 ];
M_.mapping.p_R_RG_reset.eqidx = [49 52 ];
M_.mapping.p_G_RG_reset.eqidx = [50 53 ];
M_.mapping.p_U_RG_reset.eqidx = [51 54 ];
M_.mapping.d_y_U.eqidx = [106 ];
M_.mapping.d_i_U.eqidx = [107 ];
M_.mapping.d_pi_U.eqidx = [108 ];
M_.mapping.d_w_U.eqidx = [109 ];
M_.mapping.d_y_G.eqidx = [110 ];
M_.mapping.d_i_G.eqidx = [111 ];
M_.mapping.d_pi_G.eqidx = [112 ];
M_.mapping.d_w_G.eqidx = [113 ];
M_.mapping.d_q_G.eqidx = [114 ];
M_.mapping.eps_i_U.eqidx = [98 ];
M_.mapping.eps_i_G.eqidx = [99 ];
M_.mapping.eps_i_R.eqidx = [100 ];
M_.mapping.eps_R.eqidx = [91 ];
M_.mapping.eps_G.eqidx = [90 ];
M_.mapping.eps_a_U.eqidx = [103 ];
M_.mapping.eps_a_G.eqidx = [104 ];
M_.mapping.eps_a_R.eqidx = [105 ];
M_.mapping.eps_uip_G.eqidx = [101 ];
M_.mapping.eps_uip_R.eqidx = [102 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 3 13 14 15 19 20 21 22 23 25 26 27 28 29 56 57 58 59 60 61 62 63 66 67 72 73 78 79 85 86 87 93 94 100 101 102 ];
M_.exo_names_orig_ord = [1:10];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(114, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(10, 1);
M_.params = NaN(68, 1);
M_.endo_trends = struct('deflator', cell(114, 1), 'log_deflator', cell(114, 1), 'growth_factor', cell(114, 1), 'log_growth_factor', cell(114, 1));
M_.NNZDerivatives = [528; 512; -1; ];
M_.static_tmp_nbr = [31; 11; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
load init_gamma_0_5.mat 
M_.params(1) = 0.99;
beta = M_.params(1);
M_.params(4) = 2;
sigma = M_.params(4);
M_.params(5) = 2;
sigma_c = M_.params(5);
M_.params(6) = 2;
varphi = M_.params(6);
M_.params(7) = 1;
kappa = M_.params(7);
M_.params(8) = 0.5;
gamma = M_.params(8);
M_.params(9) = 1/M_.params(1)-1;
i_star = M_.params(9);
M_.params(10) = 0.001;
psi = M_.params(10);
M_.params(11) = 0;
B_bar = M_.params(11);
M_.params(12) = 4;
eta = M_.params(12);
M_.params(13) = log(M_.params(12)/(M_.params(12)-1));
mu_W = M_.params(13);
M_.params(14) = 0.75;
theta_p = M_.params(14);
M_.params(15) = 0.85;
theta_W = M_.params(15);
M_.params(16) = (1-M_.params(1)*M_.params(15))*(1-M_.params(15))/(M_.params(15)*(1+M_.params(12)*M_.params(6)));
lambda_W = M_.params(16);
mubar       = log(sigma/(sigma-1)); 
M_.params(23) = log(M_.params(4)/(M_.params(4)-1));
mu_bar = M_.params(23);
M_.params(20) = 0;
zeta = M_.params(20);
M_.params(32) = 0.;
habit = M_.params(32);
M_.params(25) = 1.;
a_bar = M_.params(25);
M_.params(26) = 0.8;
rho_a = M_.params(26);
M_.params(27) = 0.01;
std_a = M_.params(27);
M_.params(17) = 0.5;
rho_m = M_.params(17);
M_.params(18) = 0.5;
rho_eps = M_.params(18);
M_.params(19) = 1.5;
phi_M = M_.params(19);
M_.params(30) = 0.125;
phi_Y = M_.params(30);
M_.params(24) = 0.0025;
stdm = M_.params(24);
M_.params(28) = 0.5;
rho_uip = M_.params(28);
M_.params(29) = 0.01;
std_uip = M_.params(29);
M_.params(2) = 0.6666666666666666;
alpha = M_.params(2);
M_.params(21) = 1;
varepsilon = M_.params(21);
M_.params(22) = M_.params(21)/(M_.params(4)-1);
Gamma = M_.params(22);
M_.params(3) = M_.params(2)^M_.params(2)*(1-M_.params(2))^(1-M_.params(2));
alphatilde = M_.params(3);
M_.params(31) = x_SS(4);
yflex = M_.params(31);
M_.params(33) = 1;
theta_U_UG = M_.params(33);
M_.params(34) = 0;
theta_G_UG = M_.params(34);
M_.params(35) = 1;
theta_U_UR = M_.params(35);
M_.params(36) = 0;
theta_R_UR = M_.params(36);
M_.params(37) = 1;
theta_U_GU = M_.params(37);
M_.params(38) = 0;
theta_G_GU = M_.params(38);
M_.params(39) = 0;
theta_R_GR = M_.params(39);
M_.params(40) = 0;
theta_G_GR = M_.params(40);
M_.params(41) = 1;
theta_U_GR = M_.params(41);
M_.params(42) = 1;
theta_U_RU = M_.params(42);
M_.params(43) = 0;
theta_R_RU = M_.params(43);
M_.params(44) = 0;
theta_R_RG = M_.params(44);
M_.params(45) = 0;
theta_G_RG = M_.params(45);
M_.params(46) = 1;
theta_U_RG = M_.params(46);
M_.params(47) = 1.5;
phi_pi_U = M_.params(47);
M_.params(48) = 1.5;
phi_pi_G = M_.params(48);
M_.params(49) = 1.5;
phi_pi_R = M_.params(49);
M_.params(50) = 0.125;
phi_Y_U = M_.params(50);
M_.params(51) = 0.125;
phi_Y_G = M_.params(51);
M_.params(52) = 0.125;
phi_Y_R = M_.params(52);
M_.params(53) = 0.5;
rho_m_U = M_.params(53);
M_.params(54) = 0.5;
rho_m_G = M_.params(54);
M_.params(55) = 0.5;
rho_eps_U = M_.params(55);
M_.params(56) = 0.5;
rho_eps_G = M_.params(56);
M_.params(57) = 0.5;
rho_uip_G = M_.params(57);
M_.params(58) = 0.8;
rho_a_U = M_.params(58);
M_.params(59) = 0.8;
rho_a_G = M_.params(59);
M_.params(60) = 0.85;
theta_p_U = M_.params(60);
M_.params(61) = 0.85;
theta_W_U = M_.params(61);
M_.params(62) = (1-M_.params(1)*M_.params(61))*(1-M_.params(61))/((1+M_.params(12)*M_.params(6))*M_.params(61));
lambda_W_U = M_.params(62);
M_.params(63) = 0.75;
theta_p_G = M_.params(63);
M_.params(64) = 0.85;
theta_W_G = M_.params(64);
M_.params(65) = (1-M_.params(1)*M_.params(64))*(1-M_.params(64))/((1+M_.params(12)*M_.params(6))*M_.params(64));
lambda_W_G = M_.params(65);
M_.params(66) = 0.65;
theta_p_R = M_.params(66);
M_.params(67) = 0.85;
theta_W_R = M_.params(67);
M_.params(68) = (1-M_.params(1)*M_.params(67))*(1-M_.params(67))/((1+M_.params(12)*M_.params(6))*M_.params(67));
lambda_W_R = M_.params(68);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(13) = x_SS(1);
oo_.steady_state(15) = x_SS(1);
oo_.steady_state(14) = x_SS(1);
oo_.steady_state(30) = x_SS(2);
oo_.steady_state(31) = x_SS(2);
oo_.steady_state(32) = x_SS(2);
oo_.steady_state(36) = x_SS(3);
oo_.steady_state(37) = x_SS(3);
oo_.steady_state(38) = x_SS(3);
oo_.steady_state(39) = x_SS(4);
oo_.steady_state(41) = x_SS(4);
oo_.steady_state(40) = x_SS(4);
oo_.steady_state(51) = x_SS(5);
oo_.steady_state(52) = x_SS(5);
oo_.steady_state(53) = x_SS(5);
oo_.steady_state(27) = x_SS(6);
oo_.steady_state(28) = x_SS(6);
oo_.steady_state(29) = x_SS(6);
oo_.steady_state(33) = x_SS(7);
oo_.steady_state(34) = x_SS(7);
oo_.steady_state(35) = x_SS(7);
oo_.steady_state(54) = x_SS(8);
oo_.steady_state(55) = x_SS(8);
oo_.steady_state(42) = x_SS(9);
oo_.steady_state(48) = x_SS(9);
oo_.steady_state(45) = x_SS(9);
oo_.steady_state(43) = x_SS(10);
oo_.steady_state(44) = x_SS(10);
oo_.steady_state(46) = x_SS(10);
oo_.steady_state(47) = x_SS(10);
oo_.steady_state(49) = x_SS(10);
oo_.steady_state(50) = x_SS(10);
oo_.steady_state(25) = M_.params(11);
oo_.steady_state(24) = M_.params(11);
oo_.steady_state(26) = M_.params(11);
oo_.steady_state(16) = 0;
oo_.steady_state(18) = 0;
oo_.steady_state(17) = 0;
oo_.steady_state(19) = M_.params(9);
oo_.steady_state(20) = M_.params(9);
oo_.steady_state(21) = M_.params(9);
oo_.steady_state(22) = M_.params(9);
oo_.steady_state(23) = M_.params(9);
oo_.steady_state(1) = 0;
oo_.steady_state(4) = 0;
oo_.steady_state(5) = 0;
oo_.steady_state(3) = 0;
oo_.steady_state(8) = 0;
oo_.steady_state(9) = 0;
oo_.steady_state(2) = 0;
oo_.steady_state(7) = 0;
oo_.steady_state(6) = 0;
oo_.steady_state(56) = 0;
oo_.steady_state(58) = 0;
oo_.steady_state(57) = 0;
oo_.steady_state(59) = M_.params(25);
oo_.steady_state(60) = M_.params(25);
oo_.steady_state(61) = M_.params(25);
oo_.steady_state(64) = x_SS(10);
oo_.steady_state(70) = x_SS(10);
oo_.steady_state(76) = x_SS(10);
oo_.steady_state(84) = x_SS(10);
oo_.steady_state(91) = x_SS(10);
oo_.steady_state(99) = x_SS(10);
oo_.steady_state(65) = x_SS(10);
oo_.steady_state(77) = x_SS(10);
oo_.steady_state(83) = x_SS(10);
oo_.steady_state(98) = x_SS(10);
oo_.steady_state(71) = x_SS(10);
oo_.steady_state(82) = x_SS(10);
oo_.steady_state(92) = x_SS(10);
oo_.steady_state(97) = x_SS(10);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
options_.steady.maxit = 10000;
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = (0.0025)^2;
load Dataset220324_erdiv100.mat;
BEG_OBS          = 1;   
END_OBS          = length(DATES);      
DATES            = DATES(BEG_OBS:END_OBS,:);
datadescr.DATES  = DATES;
datadescr.MODEL  = M_.fname;
dataseries.d_y_U  = GDP_US_Cycle(BEG_OBS:END_OBS);
datadescr.d_y_U   = 'GDP US';
dataseries.d_i_U  = FFR(BEG_OBS:END_OBS);
datadescr.d_i_U   = 'Interest Rate US';
dataseries.d_pi_U  = GDP_Def_US(BEG_OBS:END_OBS);
datadescr.d_pi_U   = 'Inflation Rate US';
dataseries.d_w_U  = Wage_US_Cycle(BEG_OBS:END_OBS);
datadescr.d_w_U   = 'Wages US';
dataseries.d_y_G  = GDP_Cycle(BEG_OBS:END_OBS);
datadescr.d_y_G   = 'GDP EA';
dataseries.d_i_G  = Euri(BEG_OBS:END_OBS);
datadescr.d_i_G   = 'Interest Rate EA';
dataseries.d_pi_G  = GDP_Def(BEG_OBS:END_OBS);
datadescr.d_pi_G   = 'Inflation Rate EA';
dataseries.d_w_G  = Wage_Cycle(BEG_OBS:END_OBS);
datadescr.d_w_G   = 'Wages US';
dataseries.d_q_G  = Exchange_r(BEG_OBS:END_OBS);
datadescr.d_q_G   = 'Exchange Rate';
save ('DYNARE_estimdata','-STRUCT','dataseries')
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.0031, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.0025, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.0071, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.0081, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.0109, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.0050, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.0051, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.0074, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.0029, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, 0.0064, 0, Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 47, 1.7958, (-Inf), Inf, 2, 1.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 48, 1.4228, (-Inf), Inf, 2, 1.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 50, 0.7403, (-Inf), Inf, 3, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 51, 0.7267, (-Inf), Inf, 3, 0.25, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 60, 0.7063, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 61, 0.6990, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 63, 0.7063, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 64, 0.6990, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 53, 0.5511, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 54, 0.5585, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 55, 0.9341, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 56, 0.9101, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 57, 0.9414, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 58, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 59, NaN, (-Inf), Inf, 1, 0.75, 0.1, NaN, NaN, NaN ];
options_.use_calibration_initialization = 1;
options_.mh_drop = 0.5;
options_.mh_nblck = 1;
options_.mh_replic = 500000;
options_.mode_compute = 1;
options_.plot_priors = 0;
options_.prior_trunc = 0;
options_.datafile = 'DYNARE_estimdata';
options_.order = 1;
var_list_ = {};
oo_recursive_=dynare_estimation(var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'DCP_D_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
